[AdvAgencySite] [Feature] Поправлена env переменная STRAPI_URL

diff --git a/src/apps/web/advertise-agency-site/Dockerfile-localtunnel-test b/src/apps/web/advertise-agency-site/Dockerfile-localtunnel-test
--- a/src/apps/web/advertise-agency-site/Dockerfile-localtunnel-test
+++ b/src/apps/web/advertise-agency-site/Dockerfile-localtunnel-test
@@ -8,11 +8,11 @@ WORKDIR /app
 COPY package.json pnpm-lock.yaml ./
 RUN pnpm install --frozen-lockfile
 
-ARG NEXT_PUBLIC_STRAPI_API_URL
+ARG NEXT_PUBLIC_STRAPI_URL
 
-RUN test -n "$NEXT_PUBLIC_STRAPI_API_URL" || (echo "ERROR: NEXT_PUBLIC_STRAPI_API_URL is not set" && exit 1)
+RUN test -n "$NEXT_PUBLIC_STRAPI_URL" || (echo "ERROR: NEXT_PUBLIC_STRAPI_URL is not set" && exit 1)
 
-ENV NEXT_PUBLIC_STRAPI_API_URL=${NEXT_PUBLIC_STRAPI_API_URL}
+ENV NEXT_PUBLIC_STRAPI_URL=${NEXT_PUBLIC_STRAPI_URL}
 
 COPY . .
 RUN pnpm build
