[AdvAgencySite] [Feature] Доработана безопасность docker-compose.yml
- В docker-compose.yml передается через аргументы адрес Strapi
- Доработан Dockerfile
- Улучшена безопасность - .env не передается в контейнер при копировании файлов

diff --git a/src/apps/web/advertise-agency-site/Dockerfile-localtunnel-test b/src/apps/web/advertise-agency-site/Dockerfile-localtunnel-test
--- a/src/apps/web/advertise-agency-site/Dockerfile-localtunnel-test
+++ b/src/apps/web/advertise-agency-site/Dockerfile-localtunnel-test
@@ -8,6 +8,12 @@ WORKDIR /app
 COPY package.json pnpm-lock.yaml ./
 RUN pnpm install --frozen-lockfile
 
+ARG NEXT_PUBLIC_STRAPI_API_URL
+
+RUN test -n "$NEXT_PUBLIC_STRAPI_API_URL" || (echo "ERROR: NEXT_PUBLIC_STRAPI_API_URL is not set" && exit 1)
+
+ENV NEXT_PUBLIC_STRAPI_API_URL=${NEXT_PUBLIC_STRAPI_API_URL}
+
 COPY . .
 RUN pnpm build
 
@@ -26,7 +32,8 @@ COPY --from=build /app/package.json ./package.json
 COPY --from=build /app/pnpm-lock.yaml ./pnpm-lock.yaml
 COPY --from=build /app/next.config.ts ./next.config.ts
 COPY --from=build /app/tsconfig.json ./tsconfig.json
-COPY --from=build /app/node_modules ./node_modules
+
+RUN pnpm install --prod --frozen-lockfile
 
 COPY scripts/entrypoint-localtunnel.sh /entrypoint-localtunnel.sh
 RUN chmod +x /entrypoint-localtunnel.sh
